### ISSUE TITLE
Improve UX for Server Setup  

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-messenger-public-server#10]
Right now the Github instructions on this repo are not accurate for setting up your own public server, we need to make the process very easy for newcomers to setup a server. They should just require a VPS and domain name? and running a few scripts to setup at most

**Comment by kawww** [comment]
Yes...I have some exp about set up vps and node. But I don't know how to set up a public server when I see the instructions =.=.. need a playbook like this...https://github.com/RavenProject/Ravencoin/blob/master/static-builds/staticbuild.md#static-linux-aarch64-builds

and I have a good idea. Now termux app support run linux on android, if loki server have package on it, one-step use. Then local chat or public chat all easy to create.

**Comment by neuroscr** [comment]
we now have https://docs.loki.network/LokiServices/Messenger/public_channel_setup/

**Comment by malicioustoker** [comment]
> we now have https://docs.loki.network/LokiServices/Messenger/public_channel_setup/

404 page

**Comment by KeeJef** [comment]
> > we now have https://docs.loki.network/LokiServices/Messenger/public_channel_setup/
> 
> 404 page

https://github.com/oxen-io/session-open-group-server/blob/master/INSTALL.md
